version: "1.0"
services:
  client:
    restart: always
    build: ./client
    volumes:
      - "./client:/app"
      - /app/node_modules
    ports:
      - "8080:8080"
    stdin_open: true
    command: npm start
  api:
    restart: always
    build: ./api
    volumes:
      - "./api:/app"
      - /app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    command: npm start
